#!/bin/bash
set -euo pipefail
mkdir -p '/mnt/user/data/media/_winswatch-lab/movies' '/mnt/user/data/media/_winswatch-lab/tv'
ln -sfn '/data/media/movies/Dune - Part Two (2024)' '/mnt/user/data/media/_winswatch-lab/movies/Dune - Part Two (2024)'
ln -sfn '/data/media/movies/Scary Movie (2000)' '/mnt/user/data/media/_winswatch-lab/movies/Scary Movie (2000)'
ln -sfn '/data/media/movies/The Holdovers (2023)' '/mnt/user/data/media/_winswatch-lab/movies/The Holdovers (2023)'
ln -sfn '/data/media/movies/Sinners (2025)' '/mnt/user/data/media/_winswatch-lab/movies/Sinners (2025)'
ln -sfn '/data/media/movies/Deadpool & Wolverine (2024)' '/mnt/user/data/media/_winswatch-lab/movies/Deadpool & Wolverine (2024)'
ln -sfn '/data/media/movies/The Dark Knight (2008)' '/mnt/user/data/media/_winswatch-lab/movies/The Dark Knight (2008)'
ln -sfn '/data/media/movies/Superbad (2007)' '/mnt/user/data/media/_winswatch-lab/movies/Superbad (2007)'
ln -sfn '/data/media/movies/Nimrods (2026)' '/mnt/user/data/media/_winswatch-lab/movies/Nimrods (2026)'
ln -sfn '/data/media/movies/Home Alone (1990)' '/mnt/user/data/media/_winswatch-lab/movies/Home Alone (1990)'
ln -sfn '/data/media/movies/Parasite (2019)' '/mnt/user/data/media/_winswatch-lab/movies/Parasite (2019)'
ln -sfn '/data/media/tv/Reacher' '/mnt/user/data/media/_winswatch-lab/tv/Reacher'
ln -sfn '/data/media/tv/Severance' '/mnt/user/data/media/_winswatch-lab/tv/Severance'
ln -sfn '/data/media/tv/The Bear' '/mnt/user/data/media/_winswatch-lab/tv/The Bear'
ln -sfn '/data/media/tv/Slow Horses' '/mnt/user/data/media/_winswatch-lab/tv/Slow Horses'
ln -sfn '/data/media/tv/The Afterparty' '/mnt/user/data/media/_winswatch-lab/tv/The Afterparty'
ls -la '/mnt/user/data/media/_winswatch-lab/movies' '/mnt/user/data/media/_winswatch-lab/tv'
